### ISSUE TITLE
Incorrect UTF-8 with high plane characters

### ISSUE THREAD

**Issue by matthiasr** [prometheus/promdash#429]
When trying to save a dashboard with a [𝚫](http://graphemica.com/%F0%9D%9A%AB) I got a 500 from the server. Server log says:

```
15688556	2015-07-03_16:21:49.50274 I, [2015-07-03T16:21:43.719763 #5]  INFO -- : Completed 500 Internal Server Error in 7ms
15688556	2015-07-03_16:21:49.50274 F, [2015-07-03T16:21:43.722726 #5] FATAL -- :
15688556	2015-07-03_16:21:49.50275 JSON::GeneratorError (source sequence is illegal/malformed utf-8):
15688556	2015-07-03_16:21:49.50275   app/controllers/dashboards_controller.rb:128:in `dashboard_params'
15688556	2015-07-03_16:21:49.50275   app/controllers/dashboards_controller.rb:85:in `block in update'
15688556	2015-07-03_16:21:49.50276   app/controllers/dashboards_controller.rb:84:in `update'
15688556	2015-07-03_16:21:49.50276
15688556	2015-07-03_16:21:49.50277
```

The string in question (legend string) was encoded as `"\ud835\udeab"` in the JSON sent by the browser.

**Comment by matthiasr** [comment]
Sending a [Δ](http://graphemica.com/%CE%94) instead works.
